name: SDK build and test

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24.18.0
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - name: "Install deps"
        run: npm ci
      - name: "Build"
        run: |
          npm run build:tsc
          npm run build:dist
      - name: "Test"
        run: npm t
