name: Publish to NPM

permissions:
  contents: read
  id-token: write # for IODC

on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@11
      - run: npm ci
      - run: npm run build:dist
      - run: npm test
      - run: node prepublish.mjs && cd dist && npm publish --provenance --access public
